### PR TITLE
Add release notes for FreeIPA 4.9.13

### PR DESCRIPTION
**Pull request by antoniotorresm**

### CODE REVIEW

**Comment by abbra** [comment]
I think we should add the following to highlights
- [#9289](https://pagure.io/freeipa/issue/9289) ([rhbz#2149344](https://bugzilla.redhat.com/show_bug.cgi?id=2149344)) Configure server affinity during replica installation
- [#9331](https://pagure.io/freeipa/issue/9331) ([rhbz#2164349](https://bugzilla.redhat.com/show_bug.cgi?id=2164349)) Better handling of the command line and web UI cert search and/or list features
- [#9427](https://pagure.io/freeipa/issue/9427) ([rhbz#2216532](https://bugzilla.redhat.com/show_bug.cgi?id=2216532)) RHEL 8.8 & 9.2 fails to create AD trust with STIG applied
- [#9448](https://pagure.io/freeipa/issue/9448) FreeIPA 4.9 KDB rejects FreeIPA 4.10 KDB-issued evidence ticket in S4U processing
- [#9433](https://pagure.io/freeipa/issue/9433) ([rhbz#2234480](https://bugzilla.redhat.com/show_bug.cgi?id=2234480)) ipa user-mod –idp-user-id fails with: attribute “ipaIdpSub” not allowed

**Comment by abbra** [comment]
I'll add changelog entries to those in pagure on Monday.

**Comment by rcritten** [comment]
These are relatively minor changes but have a big, if not necessarily visible, impact.

* https://pagure.io/freeipa/issue/9402 OTP authentication failure on s390x. This prompted us to start doing multi-arch testing
* https://pagure.io/freeipa/issue/9422  Interrupt request processing in ipadb_fill_info3() if connection to 389ds is lost. This prevents crashes during  Kerberos processing if the LDAP connection is somehow dropped.

**Comment by flo-renaud** [comment]
No additional comments, I agree with @rcritten and @abbra re. the tickets to be highlighted.

**Comment by abbra** [comment]
I added changelog entries to all mentioned tickets.

**Pull request merged**
