### PR TITLE
Lots of formatting fixes

### PR DESCRIPTION
**Pull request by jeffclay**
I started with an attempt to resolve issue #25 and being brand new to RST and Sphinx, etc. this was... interesting.  

I don't think I broke anything. I fixed all the errors that my changes generated. All in all, I think it turned out well considering the scope of the changes but I'll let the experts in documentation be the judge.

Most of the changes were made by a Python script so that I could iterate, investigate and adjust things across all the documents like applying a template. I put the exact script that is responsible for the changes on my [Github](https://github.com/jeffclay/freeipa_rst_fixes).

Just like the commits, the script is fairly straightforward, at the bottom main.py in the `process_directory` function you'll see a list of functions executed sequentially responsible for each commit of this PR. I did it this way trying to make all the changes more manageable and comprehensible.

### CODE REVIEW

**Comment by antoniotorresm** [comment]
This is an amazing work, thanks a lot!
Could you squash your commits into one (add all the titles to the single commit's message), and fix the merge conflict?

**Comment by jeffclay** [comment]
Does Github not have the option to squash commits when merging? I'm more familiar with Gitlab and figured that the multiple change specific commits would be better for change tracking and for anyone who tries to review the 11k/9k changes across 210 files.

**Comment by antoniotorresm** [comment]
That's fair, I'll squash during merge. Please fix the merge conflict with  `src/page/Build.rst `.

**Comment by abbra** [comment]
I don't think we need to squash them all. Perhaps, even better to leave as they are -- it gives a good history of changes for future. Thank you for this fundamental work!

**Comment by theS1LV3R** [comment]
This looks great! I noticed some pages are still broken, e.g. https://www.freeipa.org/pull/37/page/API_Examples

**Comment by jeffclay** [comment]
> This looks great! I noticed some pages are still broken, e.g. https://www.freeipa.org/pull/37/page/API_Examples

@theS1LV3R    Thanks. There are some spots that are going to have to be manually fixed over time. 99.9% of my changes were scripted based on pattern matching. I know for sure there are still poorly formatted lines lingering around. I found that there are instances where pattern replacements would fix some spots but then cause undesired changes elsewhere. 

The change and contribution process in this project is pretty straight forward, including local builds for testing, so it's pretty trivial to just start going through the docs and contributing changes back as necessary.

**Comment by jeffclay** [comment]
I think I've resolved the conflict properly. If needed, it isn't too much trouble for me to nuke my repo and just recreate all my changes again. That's a benefit of scripting everything! :)

**Comment by antoniotorresm** [comment]
GitHub still complains: `"This branch cannot be rebased due to conflicts"`. Could you try rebasing your local branch? Also, try to drop the merge commits such as https://github.com/freeipa/freeipa.github.io/pull/37/commits/70f8b739b63c33ce453de86219db5379b736da12.
Again, thanks a lot for your work!

**Comment by theS1LV3R** [comment]
image

Thats not what GitHub is saying for me? @antoniotorresm

**Comment by antoniotorresm** [comment]
Weird, mine is showing this: 

image

Maybe rebase and force-push?

**Comment by jeffclay** [comment]
Interesting. The reason I did a merge the way I did was because I got errors when trying to rebase upstream in to my branch.

**Comment by theS1LV3R** [comment]
I suggest merging this, and then fixing any errors as they are discovered. Otherwise I am afraid the PR is going to become stale and never be merged

**Comment by antoniotorresm** [comment]
As stated before, GitHub doesn't let me merge this PR due to conflicts. I would suggest a local rebase and force-push.

**Comment by abbra** [comment]
I rebased @jeffclay branch and cleared conflict in the `src/page/Build.rst`. Hopefully, I haven't lost changes.

**Comment by abbra** [comment]
Merged. Thank you for this contribution!

**Pull request merged**
